---
- hosts: webservers
  become: yes
  tasks:
   - name: ppa java jdk
     apt:
       repo: ppa:openjdk-r/ppa
       state: present
     when: ansible_os_family=="Debian"   
   - name: Run the equivalent of "apt-get update" as a separate step
     apt:
       update_cache: yes
     when: ansible_os_family=="Debian"

   - name: install java7 on ubuntu16
     apt:
       name: openjdk-7-jre
       state: present
     when: ansible_os_family=="Debian"   
