---
- hosts: webservers
  become: yes
  tasks:
   - name: ppa java jdk
     apt:
       name: openjdk-7-jdk
       state: present
     when: ansible_os_family=="Debian"   
   - name: update cache
     apt:
      update_cache: yes
     when: ansible_os_family=="Debian"

   - name: install java7 on ubuntu16
     apt:
       name: openjdk-7-jdk
       state: present
     when: ansible_os_family=="Debian"   
