---
- hosts: webservers
  become: yes
  tasks:
   - name: ppa java jre
   - apt_repository:
       repo: ppa:openjdk-r/ppa
       state: present
     when: ansible_os_family=="Debian"   
   - name: install openjdk-7-jre
     apt:
       name: openjdk-7-jre
       state: latest
     when: ansible_os_family=="Debian"

   - name: install java7 on ubuntu16
     apt:
       name: openjdk-7-jre
       state: present
     when: ansible_os_family=="Debian"   
