---
- hosts: webservers
  become: yes
  tasks:
  - name: display host name
    command: hostname -f
    register: myresult
  - name: display result of above task
    debug:
      msg: "{{myresult}}"
  - name: install git
    apt:
      name: git
      state: present
  when: myresult.stderr ==""