---
- hosts: webservers
  become: yes
  tasks:
  - include_tasks: file.yml
  - name: install webserver on ubuntu
    apt:
      name: apache2
      state: present

  - name: start webserver on ubuntun
    service:
      name: apache2
      state: started

  - name: copy dynamic file into all ubuntu nodes
    template:
       src: index.j2
       dest: /var/www/html/index.html
