---
- hosts: webservers
  become: yes
  tasks:
  - include_tasks: file.yml
  - name: install webser on ubuntu
    apt:
      name: apache2
      state: present

  - name: start webserver on ubuntun
    service:
      name: apache2
      state: started

  - name: copy dynamic file into ubuntu nodes
    template:
      src: index.j2
      dest: /var/ww/html/index.html
